"""Safe prompt-suggestion engine for the Memora CEO node.

Generates a human-reviewed PR suggestion when evaluation scores fall below
the accuracy threshold.  **No autonomous code mutation** — the CEO must
approve every change via the daily digest.
"""

from __future__ import annotations

import json
import logging
import textwrap
from datetime import datetime, timezone
from pathlib import Path

from memora import swarm_manager

logger = logging.getLogger("memora.optimizer")

THRESHOLD = 0.95
SUGGESTIONS_DIR = Path.home() / ".hermes" / "memora_suggestions"


def _ensure_suggestions_dir() -> Path:
    """Create the suggestions directory if missing."""
    SUGGESTIONS_DIR.mkdir(parents=True, exist_ok=True)
    return SUGGESTIONS_DIR


def _write_suggestion(score: float, golden_path: Path, prompts_path: Path) -> Path:
    """Write a human-readable suggestion file for the CEO to review.

    Returns:
        Path to the generated suggestion markdown file.
    """
    suggestion_path = _ensure_suggestions_dir() / f"prompt_suggestion_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"

    golden_snippet = ""
    if golden_path.exists():
        try:
            lines = golden_path.read_text(encoding="utf-8").splitlines()
            # Show first 20 lines so the CEO has context
            golden_snippet = "\n".join(lines[:20])
        except OSError as exc:
            logger.warning("Could not read golden dataset: %s", exc)

    current_prompt = ""
    if prompts_path.exists():
        try:
            current_prompt = prompts_path.read_text(encoding="utf-8")
        except OSError as exc:
            logger.warning("Could not read current prompts: %s", exc)

    body = textwrap.dedent(f"""\
    # Memora Prompt Improvement Suggestion

    > Generated automatically because Swarm Routing accuracy ({score:.2%}) is below the {THRESHOLD:.0%} threshold.

    ## Context

    - **Current score:** {score:.2%}
    - **Target threshold:** {THRESHOLD:.0%}
    - **Prompts file:** `{prompts_path}`
    - **Golden dataset:** `{golden_path}`

    ## Current Prompt

    ```python
    {current_prompt}
    ```

    ## Golden Dataset (first 20 lines)

    ```jsonl
    {golden_snippet}
    ```

    ## Recommended Action

    1. Review the failing cases in the golden dataset.
    2. Edit `{prompts_path}` to improve routing accuracy.
    3. Run `memora-evals` locally to verify improvement.
    4. Open a PR with the change for team review.

    ---
    _This suggestion was generated by the Memora optimizer.  It does **not** modify any source files automatically._
    """)

    suggestion_path.write_text(body, encoding="utf-8")
    logger.info("Wrote prompt suggestion to %s", suggestion_path)
    return suggestion_path


def run_optimization_loop(current_score: float) -> None:
    """Generate a human-reviewed suggestion when score is below threshold.

    If ``current_score < THRESHOLD``, this function:
    1. Writes a markdown suggestion file explaining the problem and
       showing the current prompt + golden dataset.
    2. Opens a Kanban task (Hermes or Linear) assigned to the CEO so
       the suggestion is tracked in the daily digest.
    3. **Never** modifies source code automatically.

    Args:
        current_score: The current evaluation accuracy (0.0–1.0).
    """
    if current_score >= THRESHOLD:
        logger.info(
            "Score %.3f meets threshold %.3f; skipping suggestion.",
            current_score,
            THRESHOLD,
        )
        return

    prompts_path = Path("src/memora/prompts.py")
    golden_path = Path("data/eval_golden.jsonl")

    suggestion_path = _write_suggestion(current_score, golden_path, prompts_path)

    # Create a kanban task for CEO review
    try:
        swarm_manager.trigger(
            source="optimizer",
            content=f"Swarm routing accuracy is {current_score:.2%} (below {THRESHOLD:.0%} threshold). "
                    f"Review prompt suggestion: {suggestion_path}",
            category="optimizer",
            scope="company",
            agent_role="reviewer",
        )
        logger.info(
            "Created Kanban task for CEO to review prompt suggestion (score %.3f).",
            current_score,
        )
    except Exception as exc:  # pragma: no cover
        logger.error("Failed to create optimizer Kanban task: %s", exc)
